### ISSUE TITLE
Analysis Start issue

### ISSUE THREAD

**Issue by innovation-madnext** [Orange-Cyberdefense/grepmarx#10]
### Launch Scan issue

I found an error when i **click on Launch Scan**, there is a server error: 

`Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask_login/utils.py", line 277, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/grepmarx/app/analysis/routes.py", line 99, in scans_launch
    import_rules(project.analysis, project_rules_path)
  File "/opt/grepmarx/app/analysis/util.py", line 350, in import_rules
    c_rule.repository.name
AttributeError: 'NoneType' object has no attribute 'name'`

This is exactly where it crashes:

`    for c_rule_pack in analysis.rule_packs:
        for c_rule in c_rule_pack.rules:
            src = os.path.join(RULES_PATH, c_rule.file_path)
            dst = os.path.join(
                rule_folder,
                c_rule.repository.name
                + "_"
                + c_rule.category
                + "."
                + c_rule.title
                + next(iter(RULE_EXTENSIONS)),
            )`

Because the c_rule.repository.name is None. Probably a default value could solve this? Maybe it's something different, The projects i'm trying to analyze are zip-files, not repositories. IDK

Thanks for your attention!! :)

**Comment by fxbru** [comment]
Nice finding, it happens only for custom local rules, which is still a very immature feature. I was able to reproduce the error.
