### ISSUE TITLE
Internal server Error when syncing repo

### ISSUE THREAD

**Issue by kleozzy** [Orange-Cyberdefense/grepmarx#4]
Hello,

I have setup gremarx repo to pull rules from and when i use pull latest rules now function i always get 500 Internal server error.

**Comment by fxbru** [comment]
Hi @kleozzy 

I wasn't able to reproduce the error. Could you maybe paste some logs here? If you used the docker install, you can use this command just after you encountered the 500 Internal server error:

`$ docker logs <grepmarx_container_id>`

The documentation is yet to be written, but you can for example use the following repo: 
https://github.com/returntocorp/semgrep-rules

Then click the "Sync rules" button.

**Comment by fxbru** [comment]
README has been clarified regarding the usage in 5f580aae41cf21c7c8a173b396ecc747063b9ab8.
