### ISSUE TITLE
Erro In install - Supervisor

### ISSUE THREAD

**Issue by meetgyn** [Orange-Cyberdefense/grepmarx#5]
I'm trying to climb the docker but this is error.
I already performed the installation of the supervisor on my kali linux and yet returns this error from the image
![image](https://user-images.githubusercontent.com/3695608/218448490-9b4622da-287d-4a82-8a6b-bf4a689b2c30.png)

**Comment by fxbru** [comment]
Hi @meetgyn 

Looks like an apt cache issue similar to https://github.com/ApolloAuto/apollo/issues/6743.

6c39f05 should fix it, you may want to try again after a pull on the main branch.
