### ISSUE TITLE
Rule packs and Repositories are not sync

### ISSUE THREAD

**Issue by Greedy-Wolf1230** [Orange-Cyberdefense/grepmarx#6]
I have installed grepmarx as per README file, but i am not able to get any rules and repositories.
every time i am trying to sync rules, getting this error as per screenshot.
<img width="793" alt="image" src="https://user-images.githubusercontent.com/22655049/226857096-7bc90952-d5df-4f06-a730-1922d26094c3.png">

**Comment by villu164** [comment]
Try adding https://github.com/returntocorp/semgrep-rules.git to repositories

https://github.com/Orange-Cyberdefense/grepmarx/issues/4#issuecomment-1430464954

**Comment by samymahi** [comment]
If you have installed grepmarx on your Mac following the Docker procedure, you may encounter issues related to the absence of the "extract.json" file. In this case, it is recommended to create this file at the root of your project. 

Additionally, if you encounter other errors, you may resolve them by using only grepmarx rules that apply to your programming language.

To generate these rules, you can use the following command (replace "C" with your programming language):
```js
for (let i = 1; i < document.getElementById('rules-list-table').getElementsByTagName('tr').length; i++) {
  if (document.getElementById('rules-list-table').getElementsByTagName('tr')[i].getElementsByTagName('td')[4].innerText === 'C') {
    document.getElementById('rules-list-table').getElementsByTagName('tr')[i].getElementsByTagName('td')[0].getElementsByTagName('input')[0].click();
  }
}
```

I'm glad to hear that the previous actions helped solve your problems.

**Comment by fxbru** [comment]
README has been updated to clarify this in 5f580aae41cf21c7c8a173b396ecc747063b9ab8.
