### ISSUE TITLE
Feature requests | Rule Packs

### ISSUE THREAD

**Issue by gbiagomba** [Orange-Cyberdefense/grepmarx#8]
Hello,

Hope all is well - i want to ask for a feature to be added to the rule pack. Is it possible to have the analysis rules be auto selected when the applicable languages are toggled? Meaning if I select `generic` from  `Applicable Languages`, the tool automatically checks-in all the `generic` rules in the `Select analysis rules`. Also is it possible to have a more granular search box where I can apply filters to what languages I want in the analysis rules.?

Thank you for your help!

**Comment by fxbru** [comment]
Hi @gbiagomba ,

I'm not sure if a automatically selecting all rules applicable to the language when defining the rule pack's language is the best approach. 

Let's suppose you want to create a rule pack to detect only injection vulnerabilities for Java: 

- Case 1: You create the new rule pack, then select Java, all Java rules are ticked. You have to manually untick all rules not related to injection vulnerabilities. 
- Case 2: You create the new rule pack, tick the rules you need. Then you select the language: all Java rules are now ticked, and you have to do all the selection again.

But there is definitely an improvement needed here. I was thinking about two possibilities, maybe both:
1. Have default / uneditable rule packs for each supported language, containing all rules for the corresponding language and that updates automatically when new rules are added.
2. Improve the table filtering to make language filtering more convenient. This is close to your second suggestion.

What do you think about it?

**As a workaround**, here is how you can (not so) easily create rule packs containing all rules for a specific language:
1. Create a new rule pack
2. Define the supported language
3. Filter the rule table to display only rules for the language. In the search box, enter:
	"java." for Java (notice the dot at the end)
	"javascript." for JavaScript
	".c." for C
	... so in fact you filter on the rule's category
4. Click on the "select all" button at the top left of the rule table
5. Click on the Save button to register the rule pack

I know it looks painful, but it usually takes me less than 5 minutes to do this for all languages.

**Comment by fxbru** [comment]
Rule filtering by language has been added, you might want to try out release v0.5.6.
