### ISSUE TITLE
Constantly getting  "No such file or directory: '/opt/grepmarx/data/projects/1/extract.json'"

### ISSUE THREAD

**Issue by R3zk0n** [Orange-Cyberdefense/grepmarx#9]
Clean build and rebuild the docker but every time i start a new scan, I appear to get 
No such file or directory: '/opt/grepmarx/data/projects/1/extract.json' in the docker logs

Also while im here, the regex to git clone from a private repo is broken, which makes the git clone to the repo not work, I adjusted it to work and ill submit a PR soon for it once i verify it

**Comment by fxbru** [comment]
Thanks for the report!

Fixed with 202c4751acf67a7985c0d4facf277e5d18e7744d.
You may want to try out release v0.5.6.
